server:
  port: 8081
spring:
  mirai:
    event:
      corePoolSize: 5
      maxPoolSize: 200
      keepAliveTime: 2000
      workQueueSize: 512
    plugin-list:
      - net.lz1998.mirai.plugin.DemoPlugin